### PR TITLE
Allow concurrent code eval

### PR DESCRIPTION
**Pull request by brandonjoyce**
Hypothetical solution to eval being a bottleneck.

### CODE REVIEW

**Comment by rrebane** [comment]
Hi. As mentioned in https://github.com/sonerdy/double/pull/39#issuecomment-862078301, these changes fixed the problem for me. Would you consider these changes to be ready for getting merged and eventually getting into the next release?

**Comment by brandonjoyce** [comment]
> Hi. As mentioned in https://github.com/sonerdy/double/pull/39#issuecomment-862078301, these changes fixed the problem for me. Would you consider these changes to be ready for getting merged and eventually getting into the next release?

Hey! Sorry for the delay. Yep, I'll get this merged and cut a release this weekend.

**Comment by rrebane** [comment]
No problem. As long as it eventually gets released. Thank you for your help!

**Comment by brandonjoyce** [comment]
This has been released as `0.8.1`

**Pull request merged**
